<?php

namespace BasketBundle\Entity;

/**
 * FingeringBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FingeringBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
