<?php

namespace BasketBundle\Entity;

/**
 * FingeringBasketsFingeringsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FingeringBasketsFingeringsRepository extends \Doctrine\ORM\EntityRepository
{
}
