(function (Translator) {
    // tr
    Translator.add("group.edit.submit", "Grubu G\u00fcncelle", "FOSUserBundle", "tr");
    Translator.add("group.show.name", "Grup Ad\u0131", "FOSUserBundle", "tr");
    Translator.add("group.new.submit", "Grup Yarat", "FOSUserBundle", "tr");
    Translator.add("group.flash.updated", "Grup G\u00fcncellendi", "FOSUserBundle", "tr");
    Translator.add("group.flash.created", "Grup Yarat\u0131ld\u0131", "FOSUserBundle", "tr");
    Translator.add("group.flash.deleted", "Grup Silindi", "FOSUserBundle", "tr");
    Translator.add("security.login.username", "Kullan\u0131c\u0131 ad\u0131", "FOSUserBundle", "tr");
    Translator.add("security.login.password", "Parola", "FOSUserBundle", "tr");
    Translator.add("security.login.remember_me", "Beni hat\u0131rla", "FOSUserBundle", "tr");
    Translator.add("security.login.submit", "Giri\u015f", "FOSUserBundle", "tr");
    Translator.add("profile.show.username", "Kullan\u0131c\u0131 ad\u0131", "FOSUserBundle", "tr");
    Translator.add("profile.show.email", "E-posta adresi", "FOSUserBundle", "tr");
    Translator.add("profile.edit.submit", "G\u00fcncelle", "FOSUserBundle", "tr");
    Translator.add("profile.flash.updated", "Profil G\u00fcncellendi", "FOSUserBundle", "tr");
    Translator.add("change_password.submit", "Parolay\u0131 De\u011fi\u015ftir", "FOSUserBundle", "tr");
    Translator.add("change_password.flash.success", "Parola de\u011fi\u015ftirildi", "FOSUserBundle", "tr");
    Translator.add("registration.check_email", "%email% adresine hesab\u0131n\u0131z\u0131 aktive etmek i\u00e7in kullanaca\u011f\u0131n\u0131z aktivasyon linkini bar\u0131nd\u0131ran bir e-posta g\u00f6nderildi.", "FOSUserBundle", "tr");
    Translator.add("registration.confirmed", "Tebrikler %username%. Hesab\u0131n\u0131z \u015fu anda aktifle\u015ftirildi.", "FOSUserBundle", "tr");
    Translator.add("registration.back", "As\u0131l sayfaya geri d\u00f6n.", "FOSUserBundle", "tr");
    Translator.add("registration.submit", "Kay\u0131t ol", "FOSUserBundle", "tr");
    Translator.add("registration.flash.user_created", "Kullan\u0131c\u0131 ba\u015far\u0131yla yarat\u0131ld\u0131", "FOSUserBundle", "tr");
    Translator.add("registration.email.subject", "Ho\u015fgeldin %username%!", "FOSUserBundle", "tr");
    Translator.add("registration.email.message", "Ho\u015fgeldiniz %username%!\n\nHesab\u0131n\u0131z\u0131n aktivasyonunu tamamlamak i\u00e7in l\u00fctfen  %confirmationUrl%\nadresini ziyaret ediniz.\n\nTe\u015fekk\u00fcrler,\nWeb Tak\u0131m\u0131.\n", "FOSUserBundle", "tr");
    Translator.add("resetting.password_already_requested", "Son 24 saat i\u00e7erisinde bu kullan\u0131c\u0131 parola i\u00e7in istekte bulunmu\u015f.", "FOSUserBundle", "tr");
    Translator.add("resetting.check_email", "%email% adresine parolan\u0131z\u0131 s\u0131f\u0131rlama adresi bulunan bir e-posta g\u00f6nderildi.", "FOSUserBundle", "tr");
    Translator.add("resetting.request.username", "Kullan\u0131c\u0131 ad\u0131 ya da e-posta adresi", "FOSUserBundle", "tr");
    Translator.add("resetting.request.submit", "Parolay\u0131 S\u0131f\u0131rla", "FOSUserBundle", "tr");
    Translator.add("resetting.reset.submit", "Parolay\u0131 de\u011fi\u015ftir", "FOSUserBundle", "tr");
    Translator.add("resetting.flash.success", "Parola ba\u015far\u0131yla de\u011fi\u015ftirildi", "FOSUserBundle", "tr");
    Translator.add("resetting.email.subject", "Parola Yenileme", "FOSUserBundle", "tr");
    Translator.add("resetting.email.message", "Merhaba  %username%!\n\nParolan\u0131z\u0131 yenilemek i\u00e7in  %confirmationUrl%\nadresini ziyaret ediniz.\n\nTe\u015fekk\u00fcrler,\nWeb Tak\u0131m\u0131.\n", "FOSUserBundle", "tr");
    Translator.add("layout.logout", "\u00c7\u0131k\u0131\u015f", "FOSUserBundle", "tr");
    Translator.add("layout.login", "Giri\u015f", "FOSUserBundle", "tr");
    Translator.add("layout.register", "Kay\u0131t ol", "FOSUserBundle", "tr");
    Translator.add("layout.logged_in_as", "%username% olarak giri\u015f yap\u0131ld\u0131", "FOSUserBundle", "tr");
    Translator.add("form.group_name", "Gurup Ad\u0131", "FOSUserBundle", "tr");
    Translator.add("form.username", "Kullan\u0131c\u0131 ad\u0131", "FOSUserBundle", "tr");
    Translator.add("form.email", "E-posta adresi", "FOSUserBundle", "tr");
    Translator.add("form.current_password", "Ge\u00e7erli Parola", "FOSUserBundle", "tr");
    Translator.add("form.password", "Parola", "FOSUserBundle", "tr");
    Translator.add("form.password_confirmation", "Onay", "FOSUserBundle", "tr");
    Translator.add("form.new_password", "Yeni Parola", "FOSUserBundle", "tr");
    Translator.add("form.new_password_confirmation", "Onay", "FOSUserBundle", "tr");
})(Translator);
