(function (Translator) {
    // hr
    Translator.add("group.edit.submit", "A\u017euriraj grupu", "FOSUserBundle", "hr");
    Translator.add("group.show.name", "Ime grupe", "FOSUserBundle", "hr");
    Translator.add("group.new.submit", "Spremi grupu", "FOSUserBundle", "hr");
    Translator.add("group.flash.updated", "Grupa je uspje\u0161no a\u017eurirana", "FOSUserBundle", "hr");
    Translator.add("group.flash.created", "Grupa je uspje\u0161no kreirana", "FOSUserBundle", "hr");
    Translator.add("group.flash.deleted", "Grupa je uspje\u0161no spremljena", "FOSUserBundle", "hr");
    Translator.add("security.login.username", "Korisni\u010dko ime", "FOSUserBundle", "hr");
    Translator.add("security.login.password", "Lozinka", "FOSUserBundle", "hr");
    Translator.add("security.login.remember_me", "Zapamti me", "FOSUserBundle", "hr");
    Translator.add("security.login.submit", "Prijava", "FOSUserBundle", "hr");
    Translator.add("profile.show.username", "Korisni\u010dko ime", "FOSUserBundle", "hr");
    Translator.add("profile.show.email", "Email", "FOSUserBundle", "hr");
    Translator.add("profile.edit.submit", "A\u017euriraj", "FOSUserBundle", "hr");
    Translator.add("profile.flash.updated", "Profil je uspje\u0161no a\u017euriran", "FOSUserBundle", "hr");
    Translator.add("change_password.submit", "Izmijeni lozinku", "FOSUserBundle", "hr");
    Translator.add("change_password.flash.success", "Lozinka je uspje\u0161no spremljena", "FOSUserBundle", "hr");
    Translator.add("registration.check_email", "Na %email% smo vam poslali poruku s poveznicom za aktivaciju. Korisni\u010dki ra\u010dun aktivirate klikom na tu poveznicu.", "FOSUserBundle", "hr");
    Translator.add("registration.confirmed", "Pozdrav %username%, va\u0161 korisni\u010dki ra\u010dun je sada aktiviran.", "FOSUserBundle", "hr");
    Translator.add("registration.back", "Natrag na polaznu stranicu.", "FOSUserBundle", "hr");
    Translator.add("registration.submit", "Registracija", "FOSUserBundle", "hr");
    Translator.add("registration.flash.user_created", "Korisni\u010dki ra\u010dun je uspje\u0161no kreiran", "FOSUserBundle", "hr");
    Translator.add("registration.email.subject", "Aktivacija korisni\u010dkog ra\u010duna", "FOSUserBundle", "hr");
    Translator.add("registration.email.message", "Pozdrav %username%!\n\nZa aktivaciju korisni\u010dkog ra\u010duna molimo kliknite na %confirmationUrl%\n\nPozdrav,\nAutori stranice\n", "FOSUserBundle", "hr");
    Translator.add("resetting.password_already_requested", "U posljednja 24 sata ste ve\u0107 poslali zahtjev za resetiranjem lozinke.", "FOSUserBundle", "hr");
    Translator.add("resetting.check_email", "Na %email%  smo vam poslali poruku s poveznicom za promjenu lozinke. Lozinku resetirajte klikom na tu poveznicu.", "FOSUserBundle", "hr");
    Translator.add("resetting.request.username", "Korisni\u010dko ime", "FOSUserBundle", "hr");
    Translator.add("resetting.request.submit", "Izmijeni lozinku", "FOSUserBundle", "hr");
    Translator.add("resetting.reset.submit", "Spremi lozinku", "FOSUserBundle", "hr");
    Translator.add("resetting.flash.success", "Lozinka je uspje\u0161no spremljena", "FOSUserBundle", "hr");
    Translator.add("resetting.email.subject", "Promjena lozinke", "FOSUserBundle", "hr");
    Translator.add("resetting.email.message", "Pozdrav %username%!\n\nZa promjenu lozinke molimo kliknite na %confirmationUrl%\n\nPozdrav,\nAutori stranice\n", "FOSUserBundle", "hr");
    Translator.add("layout.logout", "Odjava", "FOSUserBundle", "hr");
    Translator.add("layout.login", "Prijava", "FOSUserBundle", "hr");
    Translator.add("layout.register", "Registracija", "FOSUserBundle", "hr");
    Translator.add("layout.logged_in_as", "Prijavljen kao %username%", "FOSUserBundle", "hr");
    Translator.add("form.group_name", "Ime grupe", "FOSUserBundle", "hr");
    Translator.add("form.username", "Korisni\u010dko ime", "FOSUserBundle", "hr");
    Translator.add("form.email", "Email", "FOSUserBundle", "hr");
    Translator.add("form.current_password", "Trenutna lozinka", "FOSUserBundle", "hr");
    Translator.add("form.password", "Lozinka", "FOSUserBundle", "hr");
    Translator.add("form.password_confirmation", "Potvrda lozinke", "FOSUserBundle", "hr");
    Translator.add("form.new_password", "Nova lozinka", "FOSUserBundle", "hr");
    Translator.add("form.new_password_confirmation", "Potvrda lozinke", "FOSUserBundle", "hr");
})(Translator);
