(function (Translator) {
    // fr
    Translator.add("fos_js_routing_js", "\/js\/routing.{_format}", "routes", "fr");
    Translator.add("fos_user_change_password", "\/profile\/change-password", "routes", "fr");
    Translator.add("fos_user_profile_edit", "\/profile\/edit", "routes", "fr");
    Translator.add("fos_user_profile_show", "\/profile\/", "routes", "fr");
    Translator.add("fos_user_registration_check_email", "\/register\/check-email", "routes", "fr");
    Translator.add("fos_user_registration_confirm", "\/register\/confirm\/{token}", "routes", "fr");
    Translator.add("fos_user_registration_confirmed", "\/register\/confirmed", "routes", "fr");
    Translator.add("fos_user_registration_register", "\/register\/", "routes", "fr");
    Translator.add("fos_user_resetting_check_email", "\/resetting\/check-email", "routes", "fr");
    Translator.add("fos_user_resetting_request", "\/resetting\/request", "routes", "fr");
    Translator.add("fos_user_resetting_reset", "\/resetting\/reset\/{token}", "routes", "fr");
    Translator.add("fos_user_resetting_send_email", "\/resetting\/send-email", "routes", "fr");
    Translator.add("fos_user_security_check", "\/login_check", "routes", "fr");
    Translator.add("fos_user_security_login", "\/login", "routes", "fr");
    Translator.add("fos_user_security_logout", "\/logout", "routes", "fr");
    Translator.add("site_homepage", "\/", "routes", "fr");
    Translator.add("site_instrument_set", "\/site_instrument_set\/{instrument}", "routes", "fr");
    Translator.add("site_neck", "\/manche\/{instrumentId}-{instrumentName}", "routes", "fr");
    Translator.add("site_realbook", "\/realbook\/tout\/{firstletter}", "routes", "fr");
    Translator.add("site_realbook_download", "\/realbook\/telecharcher\/{tune}\/{realbook}", "routes", "fr");
    Translator.add("site_realbook_generate", "\/realbook\/generate", "routes", "fr");
    Translator.add("site_realbook_tune", "\/realbook\/morceau\/{tune}\/{realbook}", "routes", "fr");
    Translator.add("site_rootscale_index", "\/echelle-tonique\/{scale}\/{root}", "routes", "fr");
    Translator.add("site_rootscale_instrumented_index", "\/manche\/{instrumentId}-{instrumentName}\/echelle-tonique\/{scale}\/{root}", "routes", "fr");
    Translator.add("site_scale_descriptor_show", "\/echelle\/descripteur\/{descriptor_name}", "routes", "fr");
    Translator.add("site_scale_index", "\/echelle", "routes", "fr");
    Translator.add("site_scale_instrumented_index", "\/manche\/{instrumentId}-{instrumentName}\/echelle", "routes", "fr");
    Translator.add("site_scale_instrumented_show", "\/manche\/{instrumentId}-{instrumentName}\/echelle\/{scale_name}", "routes", "fr");
    Translator.add("site_scale_show", "\/echelle\/{scale_name}", "routes", "fr");
})(Translator);
