(function (Translator) {
    // fr
    Translator.add("A", "La", "messages", "fr");
    Translator.add("A#", "La#", "messages", "fr");
    Translator.add("A##", "La##", "messages", "fr");
    Translator.add("Ab", "Lab", "messages", "fr");
    Translator.add("Abb", "Labb", "messages", "fr");
    Translator.add("Available necks", "Manches disponibles", "messages", "fr");
    Translator.add("B", "Si", "messages", "fr");
    Translator.add("B#", "Si#", "messages", "fr");
    Translator.add("B##", "Si##", "messages", "fr");
    Translator.add("Bb", "Sib", "messages", "fr");
    Translator.add("Bbb", "Sibb", "messages", "fr");
    Translator.add("C", "Do", "messages", "fr");
    Translator.add("C#", "Do#", "messages", "fr");
    Translator.add("C##", "Do##", "messages", "fr");
    Translator.add("Cb", "Dob", "messages", "fr");
    Translator.add("Cbb", "Dobb", "messages", "fr");
    Translator.add("D", "Re", "messages", "fr");
    Translator.add("D#", "Re#", "messages", "fr");
    Translator.add("D##", "Re##", "messages", "fr");
    Translator.add("Db", "Reb", "messages", "fr");
    Translator.add("Dbb", "Rebb", "messages", "fr");
    Translator.add("Diagram:", "Diagram:", "messages", "fr");
    Translator.add("E", "Mi", "messages", "fr");
    Translator.add("E#", "Mi#", "messages", "fr");
    Translator.add("E##", "E##", "messages", "fr");
    Translator.add("Eb", "Mib", "messages", "fr");
    Translator.add("Ebb", "Mibb", "messages", "fr");
    Translator.add("F", "Fa", "messages", "fr");
    Translator.add("F#", "Fa#", "messages", "fr");
    Translator.add("F##", "Fa##", "messages", "fr");
    Translator.add("Fb", "Fab", "messages", "fr");
    Translator.add("Fbb", "Fabb", "messages", "fr");
    Translator.add("G", "Sol", "messages", "fr");
    Translator.add("G#", "Sol#", "messages", "fr");
    Translator.add("G##", "Sol##", "messages", "fr");
    Translator.add("Gb", "Solb", "messages", "fr");
    Translator.add("Gbb", "Solbb", "messages", "fr");
    Translator.add("Intervals", "Intervales", "messages", "fr");
    Translator.add("Matching root\/scale (%nbr%)", "Echelle\/tonique correspondantes (%nbr%)", "messages", "fr");
    Translator.add("No matching root scale ...", "Aucune echelle\/tonique trouv\u00e9e ...", "messages", "fr");
    Translator.add("Other roots:", "Autres toniques:", "messages", "fr");
    Translator.add("Scale in key off", "Echelle avec une tonique de", "messages", "fr");
    Translator.add("Welcome here... Jolineck is happy to provide tools for neck instrument players (as well as all kind of musician).", "Bienvenue ici... JoliNeck est heureux de fournir des outils aux joueurs d'instruments \u00e0 cordes (Ainsi qu'\u00e0 tous types de musiciens)", "messages", "fr");
    Translator.add("bass", "basse", "messages", "fr");
    Translator.add("bass 5 string (low B)", "basse 5 cordes (Basse Si)", "messages", "fr");
    Translator.add("guitar", "guitare", "messages", "fr");
    Translator.add("guitar (D A D F# B E)", "guitare (Re La Re Fa# Si Mi)", "messages", "fr");
    Translator.add("guitar (D A D G Bb D)", "guitare (Re La Re Sol Sib Re)", "messages", "fr");
    Translator.add("icon", "icone", "messages", "fr");
    Translator.add("monostring (C)", "monocorde (Do)", "messages", "fr");
    Translator.add("scale", "echelle", "messages", "fr");
    Translator.add("tagged as:", "tagged as:", "messages", "fr");
    Translator.add("ukulele soprano", "ukulele soprano", "messages", "fr");
    Translator.add("violin", "violon", "messages", "fr");
})(Translator);
