(function (Translator) {
    // sl
    Translator.add("group.edit.submit", "Shrani", "FOSUserBundle", "sl");
    Translator.add("group.show.name", "Ime skupine", "FOSUserBundle", "sl");
    Translator.add("group.new.submit", "Shrani", "FOSUserBundle", "sl");
    Translator.add("group.flash.updated", "Skupina je bila uspe\u0161no shranjena", "FOSUserBundle", "sl");
    Translator.add("group.flash.created", "Skupina je bila uspe\u0161no ustvarjena", "FOSUserBundle", "sl");
    Translator.add("group.flash.deleted", "Skupina je bila uspe\u0161no izbrisana", "FOSUserBundle", "sl");
    Translator.add("security.login.username", "Uporabni\u0161ko ime", "FOSUserBundle", "sl");
    Translator.add("security.login.password", "Geslo", "FOSUserBundle", "sl");
    Translator.add("security.login.remember_me", "Zapomni si me", "FOSUserBundle", "sl");
    Translator.add("security.login.submit", "Prijava", "FOSUserBundle", "sl");
    Translator.add("profile.show.username", "Uporabni\u0161ko ime", "FOSUserBundle", "sl");
    Translator.add("profile.show.email", "Email", "FOSUserBundle", "sl");
    Translator.add("profile.edit.submit", "Shrani", "FOSUserBundle", "sl");
    Translator.add("profile.flash.updated", "Profil je bil uspe\u0161no shranjen", "FOSUserBundle", "sl");
    Translator.add("change_password.submit", "Spremeni geslo", "FOSUserBundle", "sl");
    Translator.add("change_password.flash.success", "Geslo je bilo uspe\u0161no spremenjeno", "FOSUserBundle", "sl");
    Translator.add("registration.check_email", "Na %email% smo vam poslali sporo\u010dilo s kodo za aktivacijo. Ra\u010dun aktivirate s klikom na to povezavo.", "FOSUserBundle", "sl");
    Translator.add("registration.confirmed", "Pozdravljeni %username%, va\u0161 ra\u010dun je sedaj aktiviran.", "FOSUserBundle", "sl");
    Translator.add("registration.back", "Nazaj na prvotno stran.", "FOSUserBundle", "sl");
    Translator.add("registration.submit", "Registracija", "FOSUserBundle", "sl");
    Translator.add("registration.flash.user_created", "Uporabnik je bil uspe\u0161no ustvarjen", "FOSUserBundle", "sl");
    Translator.add("registration.email.subject", "Dobrodo\u0161li %username%!", "FOSUserBundle", "sl");
    Translator.add("registration.email.message", "Pozdravljeni %username%!\n\nZa aktivacijo ra\u010duna prosimo, obi\u0161\u010dite %confirmationUrl%\n\nLep pozdrav,\nekipa.\n", "FOSUserBundle", "sl");
    Translator.add("resetting.password_already_requested", "V zadnjih 24h ste \u017ee zahtevali spremembo gesla.", "FOSUserBundle", "sl");
    Translator.add("resetting.check_email", "Na %email% smo vam poslali sporo\u010dilo s kodo za spremembo gesla. Geslo boste spremenili po kliku na to povezavo.", "FOSUserBundle", "sl");
    Translator.add("resetting.request.username", "Uporabni\u0161ko ime", "FOSUserBundle", "sl");
    Translator.add("resetting.request.submit", "Spremeni geslo", "FOSUserBundle", "sl");
    Translator.add("resetting.reset.submit", "Spremeni geslo", "FOSUserBundle", "sl");
    Translator.add("resetting.flash.success", "Geslo je bilo uspe\u0161no spremenjeno", "FOSUserBundle", "sl");
    Translator.add("resetting.email.subject", "Sprememba gesla", "FOSUserBundle", "sl");
    Translator.add("resetting.email.message", "Pozdravljeni %username%!\n\nZa spremembo gesla prosimo, obi\u0161\u010dite %confirmationUrl%\n\nLep pozdrav,\nekipa.\n", "FOSUserBundle", "sl");
    Translator.add("layout.logout", "Odjava", "FOSUserBundle", "sl");
    Translator.add("layout.login", "Prijava", "FOSUserBundle", "sl");
    Translator.add("layout.register", "Registracija", "FOSUserBundle", "sl");
    Translator.add("layout.logged_in_as", "Prijavljen kot %username%", "FOSUserBundle", "sl");
    Translator.add("form.group_name", "Ime skupine", "FOSUserBundle", "sl");
    Translator.add("form.username", "Uporabni\u0161ko ime", "FOSUserBundle", "sl");
    Translator.add("form.email", "Email", "FOSUserBundle", "sl");
    Translator.add("form.current_password", "Trenutno geslo", "FOSUserBundle", "sl");
    Translator.add("form.password", "Geslo", "FOSUserBundle", "sl");
    Translator.add("form.password_confirmation", "Preverjanje gesla", "FOSUserBundle", "sl");
    Translator.add("form.new_password", "Novo geslo", "FOSUserBundle", "sl");
    Translator.add("form.new_password_confirmation", "Preverjanje gesla", "FOSUserBundle", "sl");
})(Translator);
