(function (Translator) {
    // fi
    Translator.add("group.edit.submit", "P\u00e4ivit\u00e4 ryhm\u00e4", "FOSUserBundle", "fi");
    Translator.add("group.show.name", "Ryhm\u00e4n nimi", "FOSUserBundle", "fi");
    Translator.add("group.new.submit", "Luo ryhm\u00e4", "FOSUserBundle", "fi");
    Translator.add("group.flash.updated", "Ryhm\u00e4 on p\u00e4ivitetty", "FOSUserBundle", "fi");
    Translator.add("group.flash.created", "Ryhm\u00e4 on luotu", "FOSUserBundle", "fi");
    Translator.add("group.flash.deleted", "Ryhm\u00e4 on poistettu", "FOSUserBundle", "fi");
    Translator.add("security.login.username", "K\u00e4ytt\u00e4j\u00e4tunnus", "FOSUserBundle", "fi");
    Translator.add("security.login.password", "Salasana", "FOSUserBundle", "fi");
    Translator.add("security.login.remember_me", "Muista minut", "FOSUserBundle", "fi");
    Translator.add("security.login.submit", "Kirjaudu", "FOSUserBundle", "fi");
    Translator.add("profile.show.username", "K\u00e4ytt\u00e4j\u00e4tunnus", "FOSUserBundle", "fi");
    Translator.add("profile.show.email", "S\u00e4hk\u00f6postiosoite", "FOSUserBundle", "fi");
    Translator.add("profile.edit.submit", "P\u00e4ivit\u00e4", "FOSUserBundle", "fi");
    Translator.add("profile.flash.updated", "Profiili on p\u00e4ivitetty", "FOSUserBundle", "fi");
    Translator.add("change_password.submit", "Vaihda salasana", "FOSUserBundle", "fi");
    Translator.add("change_password.flash.success", "Salasana on vaihdettu", "FOSUserBundle", "fi");
    Translator.add("registration.check_email", "S\u00e4hk\u00f6posti on l\u00e4hetetty osoitteeseen %email%. Se sis\u00e4lt\u00e4\u00e4 aktivointilinkin, jota klikkaamalla tunnus aktivoidaan.", "FOSUserBundle", "fi");
    Translator.add("registration.confirmed", "Onnittelut %username%, tunnuksesi on nyt aktivoitu.", "FOSUserBundle", "fi");
    Translator.add("registration.back", "Takaisin alkuper\u00e4iselle sivulle.", "FOSUserBundle", "fi");
    Translator.add("registration.submit", "Luo tunnus", "FOSUserBundle", "fi");
    Translator.add("registration.flash.user_created", "K\u00e4ytt\u00e4j\u00e4tunnus on luotu onnistuneesti", "FOSUserBundle", "fi");
    Translator.add("registration.email.subject", "Tervetuloa %username%!", "FOSUserBundle", "fi");
    Translator.add("registration.email.message", "Hei %username%!\n\nAktivoidaksesi tunnuksesi, ole hyv\u00e4 ja klikkaa %confirmationUrl%\n\nTerveisin yll\u00e4pito\n", "FOSUserBundle", "fi");
    Translator.add("resetting.password_already_requested", "T\u00e4lle k\u00e4ytt\u00e4j\u00e4lle on jo pyydetty salasanaa viimeisen 24 tunnin aikana.", "FOSUserBundle", "fi");
    Translator.add("resetting.check_email", "S\u00e4hk\u00f6posti on l\u00e4hetetty osoitteeseen %email%. Se sis\u00e4lt\u00e4\u00e4 linkin, jota klikkaamalla salasana alustetaan.", "FOSUserBundle", "fi");
    Translator.add("resetting.request.username", "K\u00e4ytt\u00e4j\u00e4tunnus tai s\u00e4hk\u00f6postiosoite", "FOSUserBundle", "fi");
    Translator.add("resetting.request.submit", "Alusta salasana", "FOSUserBundle", "fi");
    Translator.add("resetting.reset.submit", "Vaihda salasana", "FOSUserBundle", "fi");
    Translator.add("resetting.flash.success", "Salasana on alustettu onnistuneesti", "FOSUserBundle", "fi");
    Translator.add("resetting.email.subject", "Alusta salasana", "FOSUserBundle", "fi");
    Translator.add("resetting.email.message", "Hei %username%!\n\nAlustaaksesi salasanasi, ole hyv\u00e4 ja klikkaa %confirmationUrl%\n\nTerveisin yll\u00e4pito\n", "FOSUserBundle", "fi");
    Translator.add("layout.logout", "Ulos", "FOSUserBundle", "fi");
    Translator.add("layout.login", "Kirjaudu", "FOSUserBundle", "fi");
    Translator.add("layout.register", "Luo tunnus", "FOSUserBundle", "fi");
    Translator.add("layout.logged_in_as", "Kirjautuneena %username%", "FOSUserBundle", "fi");
    Translator.add("form.group_name", "Ryhm\u00e4n nimi", "FOSUserBundle", "fi");
    Translator.add("form.username", "K\u00e4ytt\u00e4j\u00e4tunnus", "FOSUserBundle", "fi");
    Translator.add("form.email", "S\u00e4hk\u00f6postiosoite", "FOSUserBundle", "fi");
    Translator.add("form.current_password", "Nykyinen salasana", "FOSUserBundle", "fi");
    Translator.add("form.password", "Salasana", "FOSUserBundle", "fi");
    Translator.add("form.password_confirmation", "Salasana uudestaan", "FOSUserBundle", "fi");
    Translator.add("form.new_password", "Uusi salasana", "FOSUserBundle", "fi");
    Translator.add("form.new_password_confirmation", "Salasana uudestaan", "FOSUserBundle", "fi");
})(Translator);
