(function (Translator) {
    // sv
    Translator.add("group.edit.submit", "Uppdatera gruppen", "FOSUserBundle", "sv");
    Translator.add("group.show.name", "Gruppnamn", "FOSUserBundle", "sv");
    Translator.add("group.new.submit", "Skapa grupp", "FOSUserBundle", "sv");
    Translator.add("group.flash.updated", "Gruppen har uppdaterats", "FOSUserBundle", "sv");
    Translator.add("group.flash.created", "Gruppen har skapats", "FOSUserBundle", "sv");
    Translator.add("group.flash.deleted", "Gruppen har tagits bort", "FOSUserBundle", "sv");
    Translator.add("security.login.username", "Anv\u00e4ndarnamn", "FOSUserBundle", "sv");
    Translator.add("security.login.password", "L\u00f6senord", "FOSUserBundle", "sv");
    Translator.add("security.login.remember_me", "Kom ih\u00e5g mig", "FOSUserBundle", "sv");
    Translator.add("security.login.submit", "Logga in", "FOSUserBundle", "sv");
    Translator.add("profile.show.username", "Anv\u00e4ndarnamn", "FOSUserBundle", "sv");
    Translator.add("profile.show.email", "Epost", "FOSUserBundle", "sv");
    Translator.add("profile.edit.submit", "Uppdatera", "FOSUserBundle", "sv");
    Translator.add("profile.flash.updated", "Profilen har uppdaterats", "FOSUserBundle", "sv");
    Translator.add("change_password.submit", "\u00c4ndra l\u00f6senord", "FOSUserBundle", "sv");
    Translator.add("change_password.flash.success", "L\u00f6senordet har \u00e4ndrats", "FOSUserBundle", "sv");
    Translator.add("registration.check_email", "Ett meddelande har skickats till %email%. Det inneh\u00e5ller en l\u00e4nk som du m\u00e5ste klicka p\u00e5 f\u00f6r att aktivera ditt konto.", "FOSUserBundle", "sv");
    Translator.add("registration.confirmed", "Grattis %username%, ditt konto \u00e4r nu aktiverat.", "FOSUserBundle", "sv");
    Translator.add("registration.back", "Tillbaka till den ursprungliga sidan.", "FOSUserBundle", "sv");
    Translator.add("registration.submit", "Registrera", "FOSUserBundle", "sv");
    Translator.add("registration.flash.user_created", "Anv\u00e4ndaren har skapats.", "FOSUserBundle", "sv");
    Translator.add("registration.email.subject", "V\u00e4lkommen %username%!", "FOSUserBundle", "sv");
    Translator.add("registration.email.message", "Hej %username%!\n\nF\u00f6r att aktivera ditt konto - v\u00e4nligen bes\u00f6k %confirmationUrl%\n\nH\u00e4lsningar,\nTeamet.\n", "FOSUserBundle", "sv");
    Translator.add("resetting.password_already_requested", "L\u00f6senordet f\u00f6r anv\u00e4ndaren har redan beg\u00e4rts inom de senaste 24 timmarna.", "FOSUserBundle", "sv");
    Translator.add("resetting.check_email", "Ett meddelande har skickats till %email%. Det inneh\u00e5ller en l\u00e4nk som du m\u00e5ste klicka p\u00e5 f\u00f6r att \u00e5terst\u00e4lla ditt l\u00f6senord.", "FOSUserBundle", "sv");
    Translator.add("resetting.request.username", "Anv\u00e4ndarnamn eller epost-adress", "FOSUserBundle", "sv");
    Translator.add("resetting.request.submit", "\u00c5terst\u00e4ll l\u00f6senord", "FOSUserBundle", "sv");
    Translator.add("resetting.reset.submit", "\u00c4ndra l\u00f6senord", "FOSUserBundle", "sv");
    Translator.add("resetting.flash.success", "L\u00f6senordet har \u00e5terst\u00e4llts", "FOSUserBundle", "sv");
    Translator.add("resetting.email.subject", "\u00c5terst\u00e4ll l\u00f6senord", "FOSUserBundle", "sv");
    Translator.add("resetting.email.message", "Hej %username%!\n\nF\u00f6r att \u00e5terst\u00e4lla ditt l\u00f6senord - v\u00e4nligen bes\u00f6k %confirmationUrl%\n\nH\u00e4lsningar,\nTeamet.\n", "FOSUserBundle", "sv");
    Translator.add("layout.logout", "Logga ut", "FOSUserBundle", "sv");
    Translator.add("layout.login", "Logga in", "FOSUserBundle", "sv");
    Translator.add("layout.register", "Registrera", "FOSUserBundle", "sv");
    Translator.add("layout.logged_in_as", "Inloggad som %username%", "FOSUserBundle", "sv");
    Translator.add("form.group_name", "Gruppnamn", "FOSUserBundle", "sv");
    Translator.add("form.username", "Anv\u00e4ndarnamn", "FOSUserBundle", "sv");
    Translator.add("form.email", "Epost", "FOSUserBundle", "sv");
    Translator.add("form.current_password", "Nuvarande l\u00f6senord", "FOSUserBundle", "sv");
    Translator.add("form.password", "L\u00f6senord", "FOSUserBundle", "sv");
    Translator.add("form.password_confirmation", "Verifiering", "FOSUserBundle", "sv");
    Translator.add("form.new_password", "Nytt l\u00f6senord", "FOSUserBundle", "sv");
    Translator.add("form.new_password_confirmation", "Verifiering", "FOSUserBundle", "sv");
})(Translator);
