(function (Translator) {
    // de
    Translator.add("group.edit.submit", "Gruppe aktualisieren", "FOSUserBundle", "de");
    Translator.add("group.show.name", "Gruppenname", "FOSUserBundle", "de");
    Translator.add("group.new.submit", "Gruppe erstellen", "FOSUserBundle", "de");
    Translator.add("group.flash.updated", "Die Gruppe wurde aktualisiert", "FOSUserBundle", "de");
    Translator.add("group.flash.created", "Die Gruppe wurde erstellt", "FOSUserBundle", "de");
    Translator.add("group.flash.deleted", "Die Gruppe wurde gel\u00f6scht", "FOSUserBundle", "de");
    Translator.add("security.login.username", "Benutzername", "FOSUserBundle", "de");
    Translator.add("security.login.password", "Passwort", "FOSUserBundle", "de");
    Translator.add("security.login.remember_me", "An mich erinnern", "FOSUserBundle", "de");
    Translator.add("security.login.submit", "Anmelden", "FOSUserBundle", "de");
    Translator.add("profile.show.username", "Benutzername", "FOSUserBundle", "de");
    Translator.add("profile.show.email", "E-Mail", "FOSUserBundle", "de");
    Translator.add("profile.edit.submit", "Benutzer aktualisieren", "FOSUserBundle", "de");
    Translator.add("profile.flash.updated", "Das Benutzerprofil wurde aktualisiert", "FOSUserBundle", "de");
    Translator.add("change_password.submit", "Passwort \u00e4ndern", "FOSUserBundle", "de");
    Translator.add("change_password.flash.success", "Das Passwort wurde ge\u00e4ndert", "FOSUserBundle", "de");
    Translator.add("registration.check_email", "Eine E-Mail wurde an %email% gesendet. Sie enth\u00e4lt einen Link, den Sie anklicken m\u00fcssen, um Ihr Benutzerkonto zu best\u00e4tigen.", "FOSUserBundle", "de");
    Translator.add("registration.confirmed", "Gl\u00fcckwunsch %username%, Ihr Benutzerkonto ist jetzt best\u00e4tigt.", "FOSUserBundle", "de");
    Translator.add("registration.back", "Zur\u00fcck zur urspr\u00fcnglichen Seite.", "FOSUserBundle", "de");
    Translator.add("registration.submit", "Registrieren", "FOSUserBundle", "de");
    Translator.add("registration.flash.user_created", "Der Benutzer wurde erfolgreich erstellt", "FOSUserBundle", "de");
    Translator.add("registration.email.subject", "Willkommen %username%!", "FOSUserBundle", "de");
    Translator.add("registration.email.message", "Hallo %username%!\n\nBesuchen Sie bitte folgende Seite, um Ihr Benutzerkonto zu best\u00e4tigen: %confirmationUrl%\n\nMit besten Gr\u00fc\u00dfen,\ndas Team.\n", "FOSUserBundle", "de");
    Translator.add("resetting.password_already_requested", "F\u00fcr diesen Benutzer wurde in den vergangenen 24 Stunden bereits ein neues Passwort beantragt.", "FOSUserBundle", "de");
    Translator.add("resetting.check_email", "Eine E-Mail wurde an %email% gesendet. Sie enth\u00e4lt einen Link, den Sie anklicken m\u00fcssen, um Ihr Passwort zur\u00fcckzusetzen.", "FOSUserBundle", "de");
    Translator.add("resetting.request.username", "Benutzername oder E-Mail-Adresse", "FOSUserBundle", "de");
    Translator.add("resetting.request.submit", "Passwort zur\u00fccksetzen", "FOSUserBundle", "de");
    Translator.add("resetting.reset.submit", "Passwort \u00e4ndern", "FOSUserBundle", "de");
    Translator.add("resetting.flash.success", "Das Passwort wurde erfolgreich zur\u00fcckgesetzt", "FOSUserBundle", "de");
    Translator.add("resetting.email.subject", "Passwort zur\u00fccksetzen", "FOSUserBundle", "de");
    Translator.add("resetting.email.message", "Hallo %username%!\n\nBesuchen Sie bitte folgende Seite, um Ihr Passwort zur\u00fcckzusetzen: %confirmationUrl%\n\nMit besten Gr\u00fc\u00dfen,\ndas Team.\n", "FOSUserBundle", "de");
    Translator.add("layout.logout", "Abmelden", "FOSUserBundle", "de");
    Translator.add("layout.login", "Anmelden", "FOSUserBundle", "de");
    Translator.add("layout.register", "Registrieren", "FOSUserBundle", "de");
    Translator.add("layout.logged_in_as", "Angemeldet als %username%", "FOSUserBundle", "de");
    Translator.add("form.group_name", "Gruppenname", "FOSUserBundle", "de");
    Translator.add("form.username", "Benutzername", "FOSUserBundle", "de");
    Translator.add("form.email", "E-Mail-Adresse", "FOSUserBundle", "de");
    Translator.add("form.current_password", "Derzeitiges Passwort", "FOSUserBundle", "de");
    Translator.add("form.password", "Passwort", "FOSUserBundle", "de");
    Translator.add("form.password_confirmation", "Passwort best\u00e4tigen", "FOSUserBundle", "de");
    Translator.add("form.new_password", "Neues Passwort", "FOSUserBundle", "de");
    Translator.add("form.new_password_confirmation", "Neues Passwort best\u00e4tigen", "FOSUserBundle", "de");
})(Translator);
