(function (Translator) {
    // eu
    Translator.add("group.edit.submit", "Talde eguneratu", "FOSUserBundle", "eu");
    Translator.add("group.show.name", "Taldearen izena", "FOSUserBundle", "eu");
    Translator.add("group.new.submit", "Taldea sortu", "FOSUserBundle", "eu");
    Translator.add("group.flash.updated", "Taldea eguneratua izan da", "FOSUserBundle", "eu");
    Translator.add("group.flash.created", "Taldea sortua izan da", "FOSUserBundle", "eu");
    Translator.add("group.flash.deleted", "Taldea ezabatua izan da", "FOSUserBundle", "eu");
    Translator.add("security.login.username", "Erabiltzaile izena", "FOSUserBundle", "eu");
    Translator.add("security.login.password", "Pasahitza", "FOSUserBundle", "eu");
    Translator.add("security.login.remember_me", "Oroitu", "FOSUserBundle", "eu");
    Translator.add("security.login.submit", "Sartu", "FOSUserBundle", "eu");
    Translator.add("profile.show.username", "Erabiltzaile izena", "FOSUserBundle", "eu");
    Translator.add("profile.show.email", "E-posta", "FOSUserBundle", "eu");
    Translator.add("profile.edit.submit", "Erabiltzailea eguneratu", "FOSUserBundle", "eu");
    Translator.add("profile.flash.updated", "Perfila eguneratua izan da", "FOSUserBundle", "eu");
    Translator.add("change_password.submit", "Pasahitza aldatu", "FOSUserBundle", "eu");
    Translator.add("change_password.flash.success", "Pasahitz ongi eguneratu da", "FOSUserBundle", "eu");
    Translator.add("registration.check_email", "E-posta bat bidali da %email% helbidera. Kontua aktibatzeko klik egin beharreko esteka zehazten da.", "FOSUserBundle", "eu");
    Translator.add("registration.confirmed", "Zorionak %username%, zure kontua aktibatua dago.", "FOSUserBundle", "eu");
    Translator.add("registration.back", "Itzuli.", "FOSUserBundle", "eu");
    Translator.add("registration.submit", "Izena eman", "FOSUserBundle", "eu");
    Translator.add("registration.flash.user_created", "Erabiltzailea ongi sortu da", "FOSUserBundle", "eu");
    Translator.add("registration.email.subject", "Ongi etorri %username%!", "FOSUserBundle", "eu");
    Translator.add("registration.email.message", "Kaixo %username%!\n\nKontuaren balidazioazioarekin jarraitzeko - ireki ondoko orria: %confirmationUrl%\n\nAdeitasunez,\nTaldea.\n", "FOSUserBundle", "eu");
    Translator.add("resetting.password_already_requested", "24 orduen barruan erabiltzaile honen pasahitza eskatua izan da.", "FOSUserBundle", "eu");
    Translator.add("resetting.check_email", "Email bat bidali zaio %email% helbideari. Pasahitza berreskuratzeko esteka zehazten da bertan.", "FOSUserBundle", "eu");
    Translator.add("resetting.request.username", "Erabiltzaile izena", "FOSUserBundle", "eu");
    Translator.add("resetting.request.submit", "Pasahitza berreskuratu", "FOSUserBundle", "eu");
    Translator.add("resetting.reset.submit", "Pasahitza aldatu", "FOSUserBundle", "eu");
    Translator.add("resetting.flash.success", "Pasahitza ongi aldatu da", "FOSUserBundle", "eu");
    Translator.add("resetting.email.subject", "Pasahitza berrezarri", "FOSUserBundle", "eu");
    Translator.add("resetting.email.message", "Kaixo %username%!\n\nPasahitza berrezartzeko egin klik esteka honetan: %confirmationUrl%\n\nAdeitasunez,\nTaldea.\n", "FOSUserBundle", "eu");
    Translator.add("layout.logout", "Irten", "FOSUserBundle", "eu");
    Translator.add("layout.login", "Sartu", "FOSUserBundle", "eu");
    Translator.add("layout.register", "Izena eman", "FOSUserBundle", "eu");
    Translator.add("layout.logged_in_as", "%username% bezala konektatua", "FOSUserBundle", "eu");
    Translator.add("form.group_name", "Taldearen izena", "FOSUserBundle", "eu");
    Translator.add("form.username", "Erabiltzaile izena", "FOSUserBundle", "eu");
    Translator.add("form.email", "E-posta", "FOSUserBundle", "eu");
    Translator.add("form.current_password", "Oraingo pasahitza", "FOSUserBundle", "eu");
    Translator.add("form.password", "Pasahitza", "FOSUserBundle", "eu");
    Translator.add("form.password_confirmation", "Errepikatu pasahitza", "FOSUserBundle", "eu");
    Translator.add("form.new_password", "Pasahitz berria", "FOSUserBundle", "eu");
    Translator.add("form.new_password_confirmation", "Errepikatu pasahitza", "FOSUserBundle", "eu");
})(Translator);
