(function (Translator) {
    // af
    Translator.add("group.edit.submit", "Opdateer Groep", "FOSUserBundle", "af");
    Translator.add("group.show.name", "Groep Naam", "FOSUserBundle", "af");
    Translator.add("group.new.submit", "Nuwe groep", "FOSUserBundle", "af");
    Translator.add("group.flash.updated", "Die groep was opgedateer", "FOSUserBundle", "af");
    Translator.add("group.flash.created", "Die groep was gemaak", "FOSUserBundle", "af");
    Translator.add("group.flash.deleted", "Die groep was verwyder", "FOSUserBundle", "af");
    Translator.add("security.login.username", "Gebruiker Naam", "FOSUserBundle", "af");
    Translator.add("security.login.password", "Wagwoord", "FOSUserBundle", "af");
    Translator.add("security.login.remember_me", "Onthou my", "FOSUserBundle", "af");
    Translator.add("security.login.submit", "Teken in", "FOSUserBundle", "af");
    Translator.add("profile.show.username", "Gebruiker Naam", "FOSUserBundle", "af");
    Translator.add("profile.show.email", "E-pos", "FOSUserBundle", "af");
    Translator.add("profile.edit.submit", "Opdateer", "FOSUserBundle", "af");
    Translator.add("profile.flash.updated", "Die profiel was opgedateer", "FOSUserBundle", "af");
    Translator.add("change_password.submit", "Verander wagwoord", "FOSUserBundle", "af");
    Translator.add("change_password.flash.success", "Die wagwoord was verander", "FOSUserBundle", "af");
    Translator.add("registration.check_emai", "'n e-pos was gestuur na %email%. Dit behels 'n aktiveerings \"link\", waarop jy moet klik om jou rekening te aktiveer", "FOSUserBundle", "af");
    Translator.add("registration.confirmed", "Geluk %username%, jou rekening is nou geaktiveer", "FOSUserBundle", "af");
    Translator.add("registration.back", "Terug na die oorsprongblad", "FOSUserBundle", "af");
    Translator.add("registration.submit", "Registreer", "FOSUserBundle", "af");
    Translator.add("registration.flash.user_created", "Die verbruiker was suksesvol gemaak", "FOSUserBundle", "af");
    Translator.add("registration.email.subject", "Welkom %username%!", "FOSUserBundle", "af");
    Translator.add("registration.email.message", "Hello %username%!\n\nOm die registrasieproses te finaliseer, besoek asseblief %confirmationUrl%\n\nGroete,\ndie Span.\n", "FOSUserBundle", "af");
    Translator.add("resetting.password_already_requested", "Die wagwoord vir hierdie gebruiker was reeds in die afgelope 24 uur aangevra", "FOSUserBundle", "af");
    Translator.add("resetting.check_email", "'n E-pos was gestuur na %email%. Die bevat 'n \"link\" waarop jy moet klik om jou wagwoord te herstel", "FOSUserBundle", "af");
    Translator.add("resetting.request.invalid_username", "Die verbruikernaam of e-pos adres %username% bestaan nie.", "FOSUserBundle", "af");
    Translator.add("resetting.request.username", "Verbruikernaam of e-pos adres", "FOSUserBundle", "af");
    Translator.add("resetting.request.submit", "Herstel wagwoord", "FOSUserBundle", "af");
    Translator.add("resetting.reset.submit", "Verander wagwoord", "FOSUserBundle", "af");
    Translator.add("resetting.flash.success", "Die wagwoord was suksesvol herstel", "FOSUserBundle", "af");
    Translator.add("resetting.email.subjet", "Herstel Wagwoord", "FOSUserBundle", "af");
    Translator.add("resetting.email.message", "Hello %username%!\n\nOm jou wagwoord te herstel, besoek asseblief %confirmationUrl%\n\nGroete,\ndie Span.\n", "FOSUserBundle", "af");
    Translator.add("layout.logout", "Sluit af", "FOSUserBundle", "af");
    Translator.add("layout.login", "Teken in", "FOSUserBundle", "af");
    Translator.add("layout.register", "Registreer", "FOSUserBundle", "af");
    Translator.add("layout.logged_in_as", "Ingeteken as %username%", "FOSUserBundle", "af");
    Translator.add("form.group_name", "Groep naam", "FOSUserBundle", "af");
    Translator.add("form.username", "Verbruiker Naam", "FOSUserBundle", "af");
    Translator.add("form.email", "E-pos", "FOSUserBundle", "af");
    Translator.add("form.current_password", "Huidige wagwoord", "FOSUserBundle", "af");
    Translator.add("form.password", "Wagwoord", "FOSUserBundle", "af");
    Translator.add("form.password_confirmation", "Herhaal wagwoord", "FOSUserBundle", "af");
    Translator.add("form.new_password", "Nuwe wagwoord", "FOSUserBundle", "af");
    Translator.add("form.new_password_confirmation", "Herhaal nuwe wagwoord", "FOSUserBundle", "af");
})(Translator);
