(function (Translator) {
    // pl
    Translator.add("group.edit.submit", "Edytuj grup\u0119", "FOSUserBundle", "pl");
    Translator.add("group.show.name", "Nazwa grupy", "FOSUserBundle", "pl");
    Translator.add("group.new.submit", "Utw\u00f3rz grup\u0119", "FOSUserBundle", "pl");
    Translator.add("group.flash.updated", "Grupa zosta\u0142a zaktualizowana", "FOSUserBundle", "pl");
    Translator.add("group.flash.created", "Grupa zosta\u0142a utworzona", "FOSUserBundle", "pl");
    Translator.add("group.flash.deleted", "Grupa zosta\u0142a usuni\u0119ta", "FOSUserBundle", "pl");
    Translator.add("security.login.username", "Nazwa u\u017cytkownika", "FOSUserBundle", "pl");
    Translator.add("security.login.password", "Has\u0142o", "FOSUserBundle", "pl");
    Translator.add("security.login.remember_me", "Nie wylogowuj mnie", "FOSUserBundle", "pl");
    Translator.add("security.login.submit", "Zaloguj", "FOSUserBundle", "pl");
    Translator.add("profile.show.username", "Nazwa u\u017cytkownika", "FOSUserBundle", "pl");
    Translator.add("profile.show.email", "E-mail", "FOSUserBundle", "pl");
    Translator.add("profile.edit.submit", "Edytuj u\u017cytkownika", "FOSUserBundle", "pl");
    Translator.add("profile.flash.updated", "Zapisano zmiany w profilu", "FOSUserBundle", "pl");
    Translator.add("change_password.submit", "Zmie\u0144 has\u0142o", "FOSUserBundle", "pl");
    Translator.add("change_password.flash.success", "Has\u0142o zosta\u0142o zmienione", "FOSUserBundle", "pl");
    Translator.add("registration.check_email", "Na adres %email% wys\u0142ano wiadomo\u015b\u0107 e-mail. Zawiera ona link, na kt\u00f3ry nale\u017cy klikn\u0105\u0107, aby aktywowa\u0107 konto.", "FOSUserBundle", "pl");
    Translator.add("registration.confirmed", "Gratulacje %username%, potwierdzi\u0142e\u015b konto.", "FOSUserBundle", "pl");
    Translator.add("registration.back", "Powr\u00f3t do poprzedniej strony.", "FOSUserBundle", "pl");
    Translator.add("registration.submit", "Zarejestruj", "FOSUserBundle", "pl");
    Translator.add("registration.flash.user_created", "Stworzono u\u017cytkownika", "FOSUserBundle", "pl");
    Translator.add("registration.email.subject", "Witaj %username%!", "FOSUserBundle", "pl");
    Translator.add("registration.email.message", "Cze\u015b\u0107 %username%!\n\nAby potwierdzi\u0107 swoje konto - prosz\u0119 przej\u015b\u0107 do %confirmationUrl%\n\nPozdrawiamy,\nZesp\u00f3\u0142.\n", "FOSUserBundle", "pl");
    Translator.add("resetting.password_already_requested", "W przeci\u0105gu ostatnich 24 godzin nast\u0105pi\u0142a ju\u017c pr\u00f3ba odzyskania has\u0142a.", "FOSUserBundle", "pl");
    Translator.add("resetting.check_email", "E-mail zosta\u0142 wys\u0142any. Zawiera on link do formularza zmiany has\u0142a.\nUwaga: Mo\u017cesz zresetowa\u0107 has\u0142o tylko jeden raz w ci\u0105gu %tokenLifetime% godzin.\n\nSprawd\u017a swoj\u0105 skrzynk\u0119 pocztow\u0105, je\u015bli jednak nie widzisz wiadomo\u015bci od nas, sprawd\u017a folder spam lub spr\u00f3buj ponownie p\u00f3\u017aniej.\n", "FOSUserBundle", "pl");
    Translator.add("resetting.request.username", "Nazwa u\u017cytkownika lub e-mail", "FOSUserBundle", "pl");
    Translator.add("resetting.request.submit", "Resetuj has\u0142o", "FOSUserBundle", "pl");
    Translator.add("resetting.reset.submit", "Zmie\u0144 has\u0142o", "FOSUserBundle", "pl");
    Translator.add("resetting.flash.success", "Has\u0142o zosta\u0142o zresetowane", "FOSUserBundle", "pl");
    Translator.add("resetting.email.subject", "Resetowanie has\u0142a", "FOSUserBundle", "pl");
    Translator.add("resetting.email.message", "Cze\u015b\u0107 %username%!\n\nAby zresetowa\u0107 has\u0142o - prosz\u0119 przej\u015b\u0107 do %confirmationUrl%\n\nPozdrawiamy,\nZesp\u00f3\u0142.\n", "FOSUserBundle", "pl");
    Translator.add("layout.logout", "Wyloguj", "FOSUserBundle", "pl");
    Translator.add("layout.login", "Zaloguj", "FOSUserBundle", "pl");
    Translator.add("layout.register", "Zarejestruj", "FOSUserBundle", "pl");
    Translator.add("layout.logged_in_as", "Zalogowano jako %username%", "FOSUserBundle", "pl");
    Translator.add("form.group_name", "Nazwa grupy", "FOSUserBundle", "pl");
    Translator.add("form.username", "Nazwa u\u017cytkownika", "FOSUserBundle", "pl");
    Translator.add("form.email", "E-mail", "FOSUserBundle", "pl");
    Translator.add("form.current_password", "Obecne has\u0142o", "FOSUserBundle", "pl");
    Translator.add("form.password", "Has\u0142o", "FOSUserBundle", "pl");
    Translator.add("form.password_confirmation", "Powt\u00f3rz has\u0142o", "FOSUserBundle", "pl");
    Translator.add("form.new_password", "Nowe has\u0142o", "FOSUserBundle", "pl");
    Translator.add("form.new_password_confirmation", "Powt\u00f3rz has\u0142o", "FOSUserBundle", "pl");
})(Translator);
