(function (Translator) {
    // lb
    Translator.add("group.edit.submit", "Grupp aktualis\u00e9ieren", "FOSUserBundle", "lb");
    Translator.add("group.show.name", "Gruppennumm", "FOSUserBundle", "lb");
    Translator.add("group.new.submit", "Grupp cre\u00e9ieren", "FOSUserBundle", "lb");
    Translator.add("group.flash.updated", "D'Grupp gouf aktualis\u00e9iert", "FOSUserBundle", "lb");
    Translator.add("group.flash.created", "D'Grupp gouf cre\u00e9iert", "FOSUserBundle", "lb");
    Translator.add("group.flash.deleted", "D'Grupp gouf gel\u00e4scht", "FOSUserBundle", "lb");
    Translator.add("security.login.username", "Benotzernumm", "FOSUserBundle", "lb");
    Translator.add("security.login.password", "Passwuert", "FOSUserBundle", "lb");
    Translator.add("security.login.remember_me", "U mech er\u00ebnneren", "FOSUserBundle", "lb");
    Translator.add("security.login.submit", "Umellen", "FOSUserBundle", "lb");
    Translator.add("profile.show.username", "Benotzernumm", "FOSUserBundle", "lb");
    Translator.add("profile.show.email", "E-Mail", "FOSUserBundle", "lb");
    Translator.add("profile.edit.submit", "Benotzer aktualis\u00e9ieren", "FOSUserBundle", "lb");
    Translator.add("profile.flash.updated", "De Benotzerprofil gouf aktualis\u00e9iert", "FOSUserBundle", "lb");
    Translator.add("change_password.submit", "Passwuert \u00e4nnern", "FOSUserBundle", "lb");
    Translator.add("change_password.flash.success", "D'Passwuert gouf ge\u00e4nnert", "FOSUserBundle", "lb");
    Translator.add("registration.check_email", "Eng E-Mail gouf un %email% gesch\u00e9ckt. Se enth\u00e4lt e Link deen s Du uklicke muss, fir D\u00e4i Benotzerkonto ze best\u00e4tegen.", "FOSUserBundle", "lb");
    Translator.add("registration.confirmed", "Gl\u00e9ckwonsch %username%, D\u00e4i Benutzerkonto ass elo best\u00e4tegt.", "FOSUserBundle", "lb");
    Translator.add("registration.submit", "Registr\u00e9ieren", "FOSUserBundle", "lb");
    Translator.add("registration.flash.user_created", "De Benotzer gouf erfollegr\u00e4ich cre\u00e9iert", "FOSUserBundle", "lb");
    Translator.add("registration.email.subject", "W\u00ebllkomm %username%!", "FOSUserBundle", "lb");
    Translator.add("registration.email.message", "Hallo %username%!\n\nFir D\u00e4i Benotzerkonto ze best\u00e4tegen, besich wann ech gelift d'S\u00e4it %confirmationUrl%\n\nMat beschte Gr\u00e9iss,\nd'Equipe.\n", "FOSUserBundle", "lb");
    Translator.add("resetting.password_already_requested", "Een neit Passwuert gouf an de vergaangene 24 Stunden fir d\u00ebse Benotzer schon emol ugefrot.", "FOSUserBundle", "lb");
    Translator.add("resetting.check_email", "Eng E-Mail gouf un %email% gesch\u00e9ckt. Se enth\u00e4lt e Link, deen s Du uklicke muss, fir D\u00e4i Passwort zer\u00e9ckzesetzen.", "FOSUserBundle", "lb");
    Translator.add("resetting.request.username", "Benotzernumm", "FOSUserBundle", "lb");
    Translator.add("resetting.request.submit", "Passwuert zer\u00e9cksetzen", "FOSUserBundle", "lb");
    Translator.add("resetting.reset.submit", "Passwuert \u00e4nnern", "FOSUserBundle", "lb");
    Translator.add("resetting.flash.success", "D'Passwuert gouf erfollegr\u00e4ich zer\u00e9ckgesat", "FOSUserBundle", "lb");
    Translator.add("resetting.email.subject", "W\u00ebllkomm %username%!", "FOSUserBundle", "lb");
    Translator.add("resetting.email.message", "Hallo %username%!\n\nFir D\u00e4i Passwuert zer\u00e9ckzesetzen, besich wann ech gelift d'S\u00e4it %confirmationUrl%\n\nMat beschte Gr\u00e9iss,\nd'Equipe.\n", "FOSUserBundle", "lb");
    Translator.add("layout.logout", "Ofmellen", "FOSUserBundle", "lb");
    Translator.add("layout.login", "Umellen", "FOSUserBundle", "lb");
    Translator.add("layout.register", "Registr\u00e9ieren", "FOSUserBundle", "lb");
    Translator.add("layout.logged_in_as", "Ugemellt als %username%", "FOSUserBundle", "lb");
    Translator.add("form.group_name", "Gruppennumm", "FOSUserBundle", "lb");
    Translator.add("form.username", "Benotzernumm", "FOSUserBundle", "lb");
    Translator.add("form.email", "E-Mail-Adress", "FOSUserBundle", "lb");
    Translator.add("form.current_password", "Aktuellt Passwuert", "FOSUserBundle", "lb");
    Translator.add("form.password", "Passwuert", "FOSUserBundle", "lb");
    Translator.add("form.password_confirmation", "Best\u00e4tegung", "FOSUserBundle", "lb");
    Translator.add("form.new_password", "Neit Passwuert", "FOSUserBundle", "lb");
    Translator.add("form.new_password_confirmation", "Best\u00e4tegung", "FOSUserBundle", "lb");
})(Translator);
