(function (Translator) {
    // hu
    Translator.add("group.edit.submit", "Csoport friss\u00edt\u00e9se", "FOSUserBundle", "hu");
    Translator.add("group.show.name", "Csoport n\u00e9v", "FOSUserBundle", "hu");
    Translator.add("group.new.submit", "Csoport l\u00e9trehoz\u00e1sa", "FOSUserBundle", "hu");
    Translator.add("group.flash.updated", "A csoport friss\u00edtve", "FOSUserBundle", "hu");
    Translator.add("group.flash.created", "A csoport l\u00e9trehozva", "FOSUserBundle", "hu");
    Translator.add("group.flash.deleted", "A csoport t\u00f6r\u00f6lve", "FOSUserBundle", "hu");
    Translator.add("security.login.username", "Felhaszn\u00e1l\u00f3n\u00e9v", "FOSUserBundle", "hu");
    Translator.add("security.login.password", "Jelsz\u00f3", "FOSUserBundle", "hu");
    Translator.add("security.login.remember_me", "Megjegyz\u00e9s", "FOSUserBundle", "hu");
    Translator.add("security.login.submit", "Bel\u00e9p\u00e9s", "FOSUserBundle", "hu");
    Translator.add("profile.show.username", "Felhaszn\u00e1l\u00f3n\u00e9v", "FOSUserBundle", "hu");
    Translator.add("profile.show.email", "E-mail", "FOSUserBundle", "hu");
    Translator.add("profile.edit.submit", "Friss\u00edt\u00e9s", "FOSUserBundle", "hu");
    Translator.add("profile.flash.updated", "A profil friss\u00edtve", "FOSUserBundle", "hu");
    Translator.add("change_password.submit", "Jelsz\u00f3 megv\u00e1ltoztaz\u00e1sa", "FOSUserBundle", "hu");
    Translator.add("change_password.flash.success", "A jelsz\u00f3 megv\u00e1ltoztatva", "FOSUserBundle", "hu");
    Translator.add("registration.check_email", "Egy e-mail lett k\u00fcldve a(z) %email% c\u00edmre. Egy aktiv\u00e1ci\u00f3s linket tartalmaz, amire r\u00e1 kell kattintani a fi\u00f3k aktiv\u00e1l\u00e1s\u00e1hoz.", "FOSUserBundle", "hu");
    Translator.add("registration.confirmed", "Gratul\u00e1lunk %username%, a fi\u00f3k visszaigazolva.", "FOSUserBundle", "hu");
    Translator.add("registration.back", "Vissza az el\u0151z\u0151 oldalra.", "FOSUserBundle", "hu");
    Translator.add("registration.submit", "Regisztr\u00e1ci\u00f3", "FOSUserBundle", "hu");
    Translator.add("registration.flash.user_created", "A felhaszn\u00e1l\u00f3 sikeresen l\u00e9trehozva", "FOSUserBundle", "hu");
    Translator.add("registration.email.subject", "\u00dcdv\u00f6z\u00f6lj\u00fck %username%!", "FOSUserBundle", "hu");
    Translator.add("registration.email.message", "Hello %username%!\n\nA fi\u00f3kja visszaigazol\u00e1s\u00e1hoz k\u00e9rj\u00fck l\u00e1togasson el a k\u00f6vetkez\u0151 linkre: %confirmationUrl%\n\n\u00dcdv\u00f6zlettel,\nthe Team.\n", "FOSUserBundle", "hu");
    Translator.add("resetting.password_already_requested", "Az elm\u00falt 24 \u00f3r\u00e1ban ehhez a felhaszn\u00e1l\u00f3hoz m\u00e1r k\u00e9rtek \u00faj jelsz\u00f3t.", "FOSUserBundle", "hu");
    Translator.add("resetting.check_email", "Egy e-mail lett k\u00fcldve a(z) %email% c\u00edmre. Egy linket tartalmaz, amire r\u00e1 kell kattintani a jesz\u00f3 lecser\u00e9l\u00e9s\u00e9hez.", "FOSUserBundle", "hu");
    Translator.add("resetting.request.username", "Felhaszn\u00e1l\u00f3n\u00e9v vagy e-mail c\u00edm", "FOSUserBundle", "hu");
    Translator.add("resetting.request.submit", "Jelsz\u00f3 lecser\u00e9l\u00e9se", "FOSUserBundle", "hu");
    Translator.add("resetting.reset.submit", "Jelsz\u00f3 megv\u00e1ltoztat\u00e1sa", "FOSUserBundle", "hu");
    Translator.add("resetting.flash.success", "A jelsz\u00f3 sikeresen lecser\u00e9lve", "FOSUserBundle", "hu");
    Translator.add("resetting.email.subject", "Jelsz\u00f3 lecser\u00e9l\u00e9se", "FOSUserBundle", "hu");
    Translator.add("resetting.email.message", "Hello %username%!\n\nA jelsz\u00f3 lecser\u00e9l\u00e9s\u00e9hez k\u00e9rj\u00fck l\u00e1togasson el a k\u00f6vetkez\u0151 linkre: %confirmationUrl%\n\n\u00dcdv\u00f6zlettel,\nthe Team.\n", "FOSUserBundle", "hu");
    Translator.add("layout.logout", "Kijelentkez\u00e9s", "FOSUserBundle", "hu");
    Translator.add("layout.login", "Bejelentkez\u00e9s", "FOSUserBundle", "hu");
    Translator.add("layout.register", "Regisztr\u00e1ci\u00f3", "FOSUserBundle", "hu");
    Translator.add("layout.logged_in_as", "Bel\u00e9pve mint %username%", "FOSUserBundle", "hu");
    Translator.add("form.group_name", "Csoport n\u00e9v", "FOSUserBundle", "hu");
    Translator.add("form.username", "Felhaszn\u00e1l\u00f3n\u00e9v", "FOSUserBundle", "hu");
    Translator.add("form.email", "E-mail", "FOSUserBundle", "hu");
    Translator.add("form.current_password", "Jelenlegi jelsz\u00f3", "FOSUserBundle", "hu");
    Translator.add("form.password", "Jelsz\u00f3", "FOSUserBundle", "hu");
    Translator.add("form.password_confirmation", "Meger\u0151s\u00edt\u00e9s", "FOSUserBundle", "hu");
    Translator.add("form.new_password", "\u00daj jelsz\u00f3", "FOSUserBundle", "hu");
    Translator.add("form.new_password_confirmation", "Meger\u0151s\u00edt\u00e9s", "FOSUserBundle", "hu");
})(Translator);
