(function (Translator) {
    // fr
    Translator.add("A", "La", "messages", "fr");
    Translator.add("A#", "La#", "messages", "fr");
    Translator.add("A##", "La##", "messages", "fr");
    Translator.add("A#\/Bb", "A#\/Bb", "messages", "fr");
    Translator.add("Ab", "Lab", "messages", "fr");
    Translator.add("Abb", "Labb", "messages", "fr");
    Translator.add("Available necks", "Manches disponibles", "messages", "fr");
    Translator.add("B", "Si", "messages", "fr");
    Translator.add("B#", "Si#", "messages", "fr");
    Translator.add("B##", "Si##", "messages", "fr");
    Translator.add("Bb", "Sib", "messages", "fr");
    Translator.add("Bbb", "Sibb", "messages", "fr");
    Translator.add("C", "Do", "messages", "fr");
    Translator.add("C#", "Do#", "messages", "fr");
    Translator.add("C##", "Do##", "messages", "fr");
    Translator.add("C#\/Db", "C#\/Db", "messages", "fr");
    Translator.add("Cb", "Dob", "messages", "fr");
    Translator.add("Cbb", "Dobb", "messages", "fr");
    Translator.add("D", "Re", "messages", "fr");
    Translator.add("D#", "Re#", "messages", "fr");
    Translator.add("D##", "Re##", "messages", "fr");
    Translator.add("D#\/Eb", "D#\/Eb", "messages", "fr");
    Translator.add("Db", "Reb", "messages", "fr");
    Translator.add("Dbb", "Rebb", "messages", "fr");
    Translator.add("Diagram:", "Diagram:", "messages", "fr");
    Translator.add("E", "Mi", "messages", "fr");
    Translator.add("E#", "Mi#", "messages", "fr");
    Translator.add("E##", "E##", "messages", "fr");
    Translator.add("Eb", "Mib", "messages", "fr");
    Translator.add("Ebb", "Mibb", "messages", "fr");
    Translator.add("F", "Fa", "messages", "fr");
    Translator.add("F#", "Fa#", "messages", "fr");
    Translator.add("F##", "Fa##", "messages", "fr");
    Translator.add("F#\/Gb", "F#\/Gb", "messages", "fr");
    Translator.add("Fb", "Fab", "messages", "fr");
    Translator.add("Fbb", "Fabb", "messages", "fr");
    Translator.add("G", "Sol", "messages", "fr");
    Translator.add("G#", "Sol#", "messages", "fr");
    Translator.add("G##", "Sol##", "messages", "fr");
    Translator.add("G#\/Ab", "G#\/Ab", "messages", "fr");
    Translator.add("Gb", "Solb", "messages", "fr");
    Translator.add("Gbb", "Solbb", "messages", "fr");
    Translator.add("Intervals", "Intervales", "messages", "fr");
    Translator.add("Major", "majeur", "messages", "fr");
    Translator.add("Matching root\/scale (%nbr%)", "Echelle\/tonique correspondantes (%nbr%)", "messages", "fr");
    Translator.add("No matching root scale ...", "Aucune echelle\/tonique trouv\u00e9e ...", "messages", "fr");
    Translator.add("Other roots:", "Autres toniques:", "messages", "fr");
    Translator.add("Scale in key off", "Echelle avec une tonique de", "messages", "fr");
    Translator.add("Welcome here... Jolineck is happy to provide tools for neck instrument players (as well as all kind of musician).", "Bienvenue ici... JoliNeck est heureux de fournir des outils aux joueurs d'instruments \u00e0 cordes (Ainsi qu'\u00e0 tous types de musiciens)", "messages", "fr");
    Translator.add("aeolian b5", "eolian b5", "messages", "fr");
    Translator.add("arabian", "arabe", "messages", "fr");
    Translator.add("auxiliary augmented (LCCTO)", "augment\u00e9 auxiliaire (LCCTO)", "messages", "fr");
    Translator.add("auxiliary diminished (LCCTO)", "diminu\u00e9 auxiliaire (LCCTO)", "messages", "fr");
    Translator.add("auxiliary diminished blues (LCCTO)", "diminu\u00e9 blues auxiliaire (LCCTO)", "messages", "fr");
    Translator.add("bass", "basse", "messages", "fr");
    Translator.add("bass 5 string (low B)", "basse 5 cordes (Basse Si)", "messages", "fr");
    Translator.add("byzantine", "byzantin", "messages", "fr");
    Translator.add("diminished", "diminu\u00e9", "messages", "fr");
    Translator.add("dorian", "dorien", "messages", "fr");
    Translator.add("dorian #4", "dorien #4", "messages", "fr");
    Translator.add("dorian b2", "dorian b2", "messages", "fr");
    Translator.add("eolian", "eolien", "messages", "fr");
    Translator.add("ethiopian tizita minor", "ethiopian tizita minor", "messages", "fr");
    Translator.add("guitar", "guitare", "messages", "fr");
    Translator.add("guitar (D A D F# B E)", "guitare (Re La Re Fa# Si Mi)", "messages", "fr");
    Translator.add("guitar (D A D G Bb D)", "guitare (Re La Re Sol Sib Re)", "messages", "fr");
    Translator.add("gypsy", "gitan", "messages", "fr");
    Translator.add("harmonic minor", "mineur harmonique", "messages", "fr");
    Translator.add("icon", "icone", "messages", "fr");
    Translator.add("indian ascending", "indien ascendant", "messages", "fr");
    Translator.add("indian descending", "indien descendant", "messages", "fr");
    Translator.add("ionian", "ionien", "messages", "fr");
    Translator.add("ionian #5", "ionien #5", "messages", "fr");
    Translator.add("japanese", "japonais", "messages", "fr");
    Translator.add("jewish", "juif", "messages", "fr");
    Translator.add("locrian", "locrien", "messages", "fr");
    Translator.add("locrian #6", "locrien #6", "messages", "fr");
    Translator.add("lydian", "lydien", "messages", "fr");
    Translator.add("lydian #2", "lydien #2", "messages", "fr");
    Translator.add("lydian #5", "lydian #5", "messages", "fr");
    Translator.add("lydian (LCCTO)", "lydien (LCCTO)", "messages", "fr");
    Translator.add("lydian augmented (LCCTO)", "lydien augment\u00e9 (LCCTO)", "messages", "fr");
    Translator.add("lydian b7 (LCCTO)", "lydien b7 (LCCTO)", "messages", "fr");
    Translator.add("lydian diminished (LCCTO)", "lydien diminu\u00e9 (LCCTO)", "messages", "fr");
    Translator.add("lydian dominant", "lydien dominant", "messages", "fr");
    Translator.add("melodic minor", "mineur m\u00e9lodique", "messages", "fr");
    Translator.add("mixolydian", "mixolydien", "messages", "fr");
    Translator.add("mixolydian b6", "mixolydien b6", "messages", "fr");
    Translator.add("monostring (C)", "monocorde (Do)", "messages", "fr");
    Translator.add("oriental", "orientale", "messages", "fr");
    Translator.add("pentatonic", "pentatonique", "messages", "fr");
    Translator.add("pentatonic major", "pentatonique majeur", "messages", "fr");
    Translator.add("pentatonic major b2", "pentatonique majeur b2", "messages", "fr");
    Translator.add("pentatonic minor", "pentatonique mineur", "messages", "fr");
    Translator.add("pentatonic minor 6", "pentatonique mineur 6", "messages", "fr");
    Translator.add("pentatonic minor b5", "pentatonique mineur b5", "messages", "fr");
    Translator.add("pentatonic minor blues", "pentatonique mineur blues", "messages", "fr");
    Translator.add("pentatonic whole tone", "pentatonique whole tone", "messages", "fr");
    Translator.add("persian", "perse", "messages", "fr");
    Translator.add("phrygian", "phrygien", "messages", "fr");
    Translator.add("phrygian dominant", "phrygien dominant", "messages", "fr");
    Translator.add("romanian", "roumaine", "messages", "fr");
    Translator.add("scale", "echelle", "messages", "fr");
    Translator.add("superlocrian", "superlocrien", "messages", "fr");
    Translator.add("tagged as:", "tagged as:", "messages", "fr");
    Translator.add("ukulele soprano", "ukulele soprano", "messages", "fr");
    Translator.add("violin", "violon", "messages", "fr");
    Translator.add("whole tone", "whole tone", "messages", "fr");
})(Translator);
