descriptor_index:
    path:     /
    defaults: { _controller: "AppBundle:Descriptor:index" }
    methods:  GET

descriptor_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Descriptor:show" }
    methods:  GET

descriptor_new:
    path:     /new
    defaults: { _controller: "AppBundle:Descriptor:new" }
    methods:  [GET, POST]

descriptor_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Descriptor:edit" }
    methods:  [GET, POST]

descriptor_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Descriptor:delete" }
    methods:  DELETE
