digit_index:
    path:     /
    defaults: { _controller: "AppBundle:Digit:index" }
    methods:  GET

digit_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Digit:show" }
    methods:  GET

digit_new:
    path:     /new
    defaults: { _controller: "AppBundle:Digit:new" }
    methods:  [GET, POST]

digit_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Digit:edit" }
    methods:  [GET, POST]

digit_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Digit:delete" }
    methods:  DELETE
