fbasket_index:
    path:     /
    defaults: { _controller: "AppBundle:FBasket:index" }
    methods:  GET

fbasket_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:FBasket:show" }
    methods:  GET

fbasket_new:
    path:     /new
    defaults: { _controller: "AppBundle:FBasket:new" }
    methods:  [GET, POST]

fbasket_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:FBasket:edit" }
    methods:  [GET, POST]

fbasket_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:FBasket:delete" }
    methods:  DELETE
