instrumentfamily_index:
    path:     /
    defaults: { _controller: "AppBundle:InstrumentFamily:index" }
    methods:  GET

instrumentfamily_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:InstrumentFamily:show" }
    methods:  GET

instrumentfamily_new:
    path:     /new
    defaults: { _controller: "AppBundle:InstrumentFamily:new" }
    methods:  [GET, POST]

instrumentfamily_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:InstrumentFamily:edit" }
    methods:  [GET, POST]

instrumentfamily_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:InstrumentFamily:delete" }
    methods:  DELETE
