rhythmsequence_index:
    path:     /
    defaults: { _controller: "AppBundle:RhythmSequence:index" }
    methods:  GET

rhythmsequence_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:RhythmSequence:show" }
    methods:  GET

rhythmsequence_new:
    path:     /new
    defaults: { _controller: "AppBundle:RhythmSequence:new" }
    methods:  [GET, POST]

rhythmsequence_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:RhythmSequence:edit" }
    methods:  [GET, POST]

rhythmsequence_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:RhythmSequence:delete" }
    methods:  DELETE
