rhythmmaterial_index:
    path:     /
    defaults: { _controller: "AppBundle:RhythmMaterial:index" }
    methods:  GET

rhythmmaterial_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:RhythmMaterial:show" }
    methods:  GET

rhythmmaterial_new:
    path:     /new
    defaults: { _controller: "AppBundle:RhythmMaterial:new" }
    methods:  [GET, POST]

rhythmmaterial_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:RhythmMaterial:edit" }
    methods:  [GET, POST]

rhythmmaterial_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:RhythmMaterial:delete" }
    methods:  DELETE
