services:
#    site.example:
#        class: SiteBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    app.menu.builder:
        class: SiteBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory","@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createScaleMenu, alias: scale }
            - { name: knp_menu.menu_builder, method: createLangMenu, alias: lang }
            - { name: knp_menu.menu_builder, method: createInstrumentMenu, alias: instrument }
            - { name: knp_menu.menu_builder, method: createUserMenu, alias: user }

