<?php

namespace AppBundle\Entity;

/**
 * DigitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DigitRepository extends \Doctrine\ORM\EntityRepository
{
}
