<?php

namespace AppBundle\Entity;

/**
 * FingeringFingerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FingeringFingerRepository extends \Doctrine\ORM\EntityRepository
{
}
