<?php

namespace AppBundle\Entity;

/**
 * FingeringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FingeringRepository extends \Doctrine\ORM\EntityRepository
{
}
