<?php

namespace AppBundle\Entity;

/**
 * FingeringOfflineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FingeringOfflineRepository extends \Doctrine\ORM\EntityRepository
{
}
