<?php

namespace AppBundle\Entity;

/**
 * InstrumentStringRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstrumentStringRepository extends \Doctrine\ORM\EntityRepository
{
}
