<?php

namespace AppBundle\Entity;

/**
 * InstrumentFamilyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstrumentFamilyRepository extends \Doctrine\ORM\EntityRepository
{
}
