<?php

namespace AppBundle\Entity;

/**
 * IntervaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntervaleRepository extends \Doctrine\ORM\EntityRepository
{
}
