<?php

namespace AppBundle\Entity;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRandom(){

        $array_all = array();
        foreach($this->findAll() as $k=>$v){
            array_push($array_all,$v->getId());
        }

        return $this->find($array_all[rand(0,count($array_all) - 1)]);
    }
}
