<?php

namespace AppBundle\Entity;

/**
 * RhythmSequenceMaterialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhythmSequenceMaterialsRepository extends \Doctrine\ORM\EntityRepository
{
}
