<?php

namespace AppBundle\Entity;

/**
 * RhythmMaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhythmMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
