<?php

namespace AppBundle\Entity;

/**
 * RhythmSequenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RhythmSequenceRepository extends \Doctrine\ORM\EntityRepository
{
}
