<?php

namespace AppBundle\Entity;

/**
 * SequenceChangesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SequenceChangesRepository extends \Doctrine\ORM\EntityRepository
{
}
