<?php

namespace AppBundle\Entity;

/**
 * TunesRealbooksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TunesRealbooksRepository extends \Doctrine\ORM\EntityRepository
{
}
