<?php
namespace AppBundle\Entity;
use Doctrine\ORM\Query\ResultSetMapping;
/**
 * WesternSystemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WesternSystemRepository extends \Doctrine\ORM\EntityRepository
{
    public function ajaxFindAllRoot(){
        $sql = "SELECT id,digit,name FROM western_system WHERE intervale = 1 ORDER BY DIGIT";
        $em = $this->getEntityManager();
        $rsm = new ResultSetMapping;
        $rsm->addScalarResult('id', 'id');
        $rsm->addScalarResult('name', 'name');
        $rsm->addScalarResult('digit', 'digit');

        $query = $em->createNativeQuery($sql, $rsm);
        return $query->getScalarResult();
    }
}
