<?php

namespace AppBundle\Entity;

/**
 * YxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YxRepository extends \Doctrine\ORM\EntityRepository
{
}
